# Generated by Django 5.1.15 on 2026-09-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_user_id_995030_idx',
            old_name='reservations_user_rese_7f7dfd_idx',
        ),
        migrations.RenameIndex(
            model_name='reservation',
            new_name='reservation_resourc_9a2f16_idx',
            old_name='reservations_resourc_62c6a8_idx',
        ),
        migrations.AddField(
            model_name='resource',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Reservations for this resource have to be approved by an office manager.'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Waiting for approval'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
    ]
